# Initialization of constants

INPUT_TYPE_URL = 'URL'
INPUT_TYPE_FILE = 'TEXT-FILE'

PROPOSED_ALGORITHM = 'INTEGRATED'
TEXT_RANK_ALGORITHM = 'TEXT-RANK'
BM_ALGORITHM = 'BM25'
TF_IDF_COSINE_ALGORITHM = 'TF-IDF-COSINE'
LCS_ALGORITHM = 'LCS'

ALGORITHM_SET = set([PROPOSED_ALGORITHM, TEXT_RANK_ALGORITHM, BM_ALGORITHM, TF_IDF_COSINE_ALGORITHM, LCS_ALGORITHM])
INPUT_TYPE_SET = set([INPUT_TYPE_URL, INPUT_TYPE_FILE])

OUTPUT_TYPE_FILE = 'FILE'
OUTPUT_TYPE_DISPLAY = 'DISPLAY'
OUTPUT_TYPE_SET = set([OUTPUT_TYPE_FILE, OUTPUT_TYPE_DISPLAY])

MAX_ITERATIONS = 100
SUMM_RATIO = 0.2
